# Generated by Django 4.2.5 on 2023-10-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_input_order_company_alter_input_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prcie',
            new_name='price',
        ),
    ]
