# Generated by Django 4.2.5 on 2023-10-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_prcie_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_order',
            name='input_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='output_order',
            name='ouput_stock',
            field=models.IntegerField(null=True),
        ),
    ]
