# Generated by Django 4.2.5 on 2023-12-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_input_order_input_stock_output_order_ouput_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output_order',
            old_name='ouput_stock',
            new_name='output_stock',
        ),
    ]
