# Generated by Django 4.2.5 on 2023-11-09 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=200)),
                ('file', models.FileField(upload_to='collect_files')),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 2, 5, 34, 923600, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
