# Generated by Django 4.2.5 on 2023-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
