# Generated by Django 4.2.5 on 2023-11-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_mywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('writer', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='freeboard_imgs/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('writer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freeboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.freeboard')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
