# Generated by Django 4.2.5 on 2023-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_freeboard_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='freeboard_imgs/%Y/%m/%d'),
        ),
    ]
