# Generated by Django 4.2.5 on 2023-12-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_freeboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='freeboard_imgs/%Y/%m/%d'),
        ),
    ]
